### ISSUE TITLE
train_single_class_ae.py : IndexError: list index out of range

### ISSUE THREAD

**Issue by Timaces** [optas/latent_3d_points#24]
Hi，thank you for your work.

when I run the code : train_single_class_ae.py ,I meet the question:

(latent_3d_points) l@l-THUNDEROBOT-PC:~/Documents/latent_3d_points-master$ python train_single_class_ae.py 
External Losses (Chamfer-EMD) cannot be loaded. Please install them first.
Give me the class name (e.g. "chair"): 'chair'
03001627
../data/shape_net_core_uniform_samples_2048/03001627
../data/shape_net_core_uniform_samples_2048/03001627
[]
Traceback (most recent call last):
  File "train_single_class_ae.py", line 38, in <module>
    all_pc_data = load_all_point_clouds_under_folder(class_dir, n_threads=8, file_ending='.ply', verbose=True)
  File "/home/l/Documents/latent_3d_points-master/src/in_out.py", line 120, in load_all_point_clouds_under_folder
    pclouds, model_ids, syn_ids = load_point_clouds_from_filenames(file_names, n_threads, loader=pc_loader, verbose=verbose)
  File "/home/l/Documents/latent_3d_points-master/src/in_out.py", line 125, in load_point_clouds_from_filenames
    pc = loader(file_names[0])[0]
IndexError: list index out of range

**Comment by Condor-G** [comment]
Hi~
I had the same problem. 
Please solve this problem first:
External Losses (Chamfer-EMD) cannot be loaded. Please install them first.

Please check whether your external/structural_losses/__init__.py or src/point_net_ae.py is running well when import modules. You can delete "try and except" and run to see the problem clearly.
After that, "IndexError: list index out of range" is not a problem.
In a word, check your import modules statements.
Maybe it can help you~
QAQ

**Comment by duanyaqi** [comment]
maybe you can try **absolute path**
`top_out_dir = '/home/latent_3d_points/data/'          # Use to save Neural-Net check-points etc`
`top_in_dir = '/home/latent_3d_points/data/shape_net_core_uniform_samples_2048/' # Top-dir of where point-clouds are stored.
`
